server:
  port: 8080

spring:
  application:
    name: json-dto-generator-api

# Configuração Swagger (Springdoc OpenAPI)
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    root: INFO
